version: "3.8"

services:

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - app1
      - app2
      - app3
      - app4
      - app5
      - app6
      - app7
    restart: always

  app:
    build: .
    image: local-whiteboard:latest
    environment:
      - INSTANCE_ID=1
    env_file:
      - .env
    restart: always

  app1:
    image: local-whiteboard:latest
    depends_on:
      - app
    environment:
      - INSTANCE_ID=2
    env_file:
      - .env
    restart: always

  app2:
    image: local-whiteboard:latest
    depends_on:
      - app
    environment:
      - INSTANCE_ID=3
    env_file:
      - .env
    restart: always

  app3:
    image: local-whiteboard:latest
    depends_on:
      - app
    environment:
      - INSTANCE_ID=4
    env_file:
      - .env
    restart: always

  app4:
    image: local-whiteboard:latest
    depends_on:
      - app
    environment:
      - INSTANCE_ID=5
    env_file:
      - .env
    restart: always

  app5:
    image: local-whiteboard:latest
    depends_on:
      - app
    environment:
      - INSTANCE_ID=6
    env_file:
      - .env
    restart: always

  app6:
    image: local-whiteboard:latest
    depends_on:
      - app
    environment:
      - INSTANCE_ID=7
    env_file:
      - .env
    restart: always

  app7:
    image: local-whiteboard:latest
    depends_on:
      - app
    environment:
      - INSTANCE_ID=8
    env_file:
      - .env
    restart: always